### ISSUE TITLE
add gzip encoding support for tfplan

### ISSUE THREAD

**Issue by chanwit** [chanwit/tf-controller#12]
We should use [compress/gzip ](https://pkg.go.dev/compress/gzip) to compress the byte content of `tfplan` so that it's possible for us to store a larger plan, as the current limitation of a Secret is 1 MB.

When storing `tfplan`, we must add an annotation to tell that we use GZIP to encode the content.

```yaml
metadata:
   annotations:
     encoding: gzip
```
