### ISSUE TITLE
Accept many Secrets / ConfigMaps for .spec.varsFrom

### ISSUE THREAD

**Issue by chanwit** [chanwit/tf-controller#29]

**Comment by phoban01** [comment]
I can take a look at this today.

Should look something like this (similar to the `HelmRelease` `valuesFrom`  field):

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: sample-stack
spec:
  path: ./
  sourceRef:
    kind: GitRepository
    name: sample-repo
  varsFrom:
  - kind: ConfigMap
    name: variables
  - kind: Secret
    name: provider-credentials
```
