### ISSUE TITLE
Health check support for long provisioned resources

### ISSUE THREAD

**Issue by chanwit** [chanwit/tf-controller#44]
Health check for external resources like Redis, RDS or other managed services like Mongo Atlas requires an extra step to perform a TCP connection to ensure that the target service is already up and running.

The Flagger project has some generic way to declare this test step, from which we could learn.

Our resources maybe something like TCP services, HTTP services. Here's a health check spec proposal.

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
spec:
  path: ./terraform
  healthChecks:
  - name: rds
    kind: TCP
    address: ${output.rds_ip_address}:3306
    timeout: 15m
  - name: nginx
    kind: HTTP
    address: https://${output.nginx_ip_address}/ping
    timeout: 15m
```

**Comment by tomhuang12** [comment]
Could you provide a little more details on what you are envisioning?

**Comment by tomhuang12** [comment]
Do you mean by flagger's [metrics analysis](https://docs.flagger.app/usage/metrics)?

**Comment by chanwit** [comment]
This part:
https://docs.flagger.app/usage/webhooks

**Comment by chanwit** [comment]
Maybe we can focus only at network-based health checks first. Something like this.

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
spec:
  path: ./terraform
  healthchecks:
  - name: rds
    kind: TCP
    address: ${output.rds_ip_address}:3306
    timeout: 15m
  - name: nginx
    kind: HTTP
    address: https://${output.nginx_ip_address}/ping
    timeout: 15m
```
